// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';

part 'user_model.g.dart';

@JsonSerializable()
class UserModel {
  String username;
  @JsonKey(toJson: _companyToJson)
  Company company;

  UserModel({
    this.username,
    this.company,
  });

  static Map<String, dynamic> _companyToJson(Company cmp) => cmp.toJson();

  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);

  Map<String, dynamic> toJson() => _$UserModelToJson(this);
}

@JsonSerializable()
class Company {
  String id;
  String name;

  Company({
    this.id,
    this.name,
  });
  factory Company.fromJson(Map<String, dynamic> json) =>
      _$CompanyFromJson(json);

  Map<String, dynamic> toJson() => _$CompanyToJson(this);
}
