// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';
part 'printing_label_model.g.dart';

@JsonSerializable()
class PrintingLabelModel {
  String id;
  String cd;
  String name;
  String type;
  String paper;
  String size;
  String printer;
  String desc;
  List<Img> imgs;

  factory PrintingLabelModel.fromJson(Map<String, dynamic> json) =>
      _$PrintingLabelModelFromJson(json);

  PrintingLabelModel({
    this.id,
    this.cd,
    this.name,
    this.type,
    this.paper,
    this.size,
    this.printer,
    this.desc,
    this.imgs,
  });
}

@JsonSerializable()
class Img {
  String url;

  Img({
    this.url,
  });

  factory Img.fromJson(Map<String, dynamic> json) => _$ImgFromJson(json);
}
