// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';
part 'material_model.g.dart';

@JsonSerializable()
class MaterialModel {
  @JsonKey(name: '_id', nullable: false)
  String id;
  @JsonKey(name: 'part_no', nullable: false)
  String partNo;
  String loc;
  String desc;
  String uom;
  double unitCost;
  @JsonKey(name: 'sap_qty', nullable: false)
  String sapQty;
  List<Img> imgs;

  factory MaterialModel.fromJson(Map<String, dynamic> json) =>
      _$MaterialModelFromJson(json);

  MaterialModel({
    this.id,
    this.partNo,
    this.loc,
    this.desc,
    this.uom,
    this.unitCost,
    this.sapQty,
    this.imgs,
  });
}

@JsonSerializable()
class Img {
  String url;

  Img({
    this.url,
  });

  factory Img.fromJson(Map<String, dynamic> json) => _$ImgFromJson(json);
}
