// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';
part 'material_model.g.dart';

@JsonSerializable()
class MaterialModel {
  @JsonKey(name: '_id', nullable: false)
  String id;
  @JsonKey(name: 'part_no', nullable: false)
  String partNo;
  String loc;
  String desc;
  String uom;
  double unitCost;
  @JsonKey(name: 'sap_qty', nullable: false)
  String sapQty;
  @JsonKey(name: 'tech_spec', nullable: false)
  String techSpec;
  @JsonKey(toJson: _imgToJson, defaultValue: [])
  List<Img> imgs;

  @JsonKey(name: 'adv_info',toJson: _advInfoToJson, defaultValue: [])
  List<InfoItem> advInfo;

  factory MaterialModel.fromJson(Map<String, dynamic> json) =>
      _$MaterialModelFromJson(json);

  static List<Map<String, dynamic>> _imgToJson(List<Img> list) =>
      list.map<Map<String, dynamic>>((item) {
        return item.toJson();
      }).toList();

  static List<Map<String, dynamic>> _advInfoToJson(List<InfoItem> list) =>
      list.map<Map<String, dynamic>>((item) {
        return item.toJson();
      }).toList();

  Map<String, dynamic> toJson() => _$MaterialModelToJson(this);

  MaterialModel({
    this.id,
    this.partNo,
    this.loc,
    this.desc,
    this.uom,
    this.unitCost,
    this.sapQty,
    this.imgs,
  });
}

@JsonSerializable()
class Img {
  String url;

  Img({
    this.url,
  });

  factory Img.fromJson(Map<String, dynamic> json) => _$ImgFromJson(json);
  Map<String, dynamic> toJson() => _$ImgToJson(this);
}

@JsonSerializable()
class InfoItem {
  String name;
  String value;

  InfoItem({
    this.name,
    this.value,
  });

  factory InfoItem.fromJson(Map<String, dynamic> json) => _$InfoItemFromJson(json);
  Map<String, dynamic> toJson() => _$InfoItemToJson(this);
}
